"""
Configuration settings for the Cricket Match Predictor project.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Base paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# Database
DATABASE_PATH = BASE_DIR / "cricket.db"
DATABASE_URL = f"sqlite:///{DATABASE_PATH}"

# Data sources - Cricsheet URLs
CRICSHEET_BASE_URL = "https://cricsheet.org/downloads/"
CRICSHEET_HOMEPAGE = "https://cricsheet.org/"
# Page that contains "The most recent matches added to the site are: ..."
CRICSHEET_MATCHES_URL = "https://cricsheet.org/matches/"
DATA_SOURCES = {
    "t20i": f"{CRICSHEET_BASE_URL}t20s_json.zip",           # All T20s (men + women internationals)
    "t20s_female": f"{CRICSHEET_BASE_URL}t20s_female_json.zip",  # Women's T20 internationals
    "all_female": f"{CRICSHEET_BASE_URL}all_female_json.zip",    # ALL women's cricket (T20+ODI+franchise)
    "all_male": f"{CRICSHEET_BASE_URL}all_male_json.zip",        # ALL men's cricket (T20+ODI+franchise - IPL, BBL, PSL, etc.)
    "wpl": f"{CRICSHEET_BASE_URL}wpl_json.zip",             # Women's Premier League (India)
    "odi": f"{CRICSHEET_BASE_URL}odis_json.zip",
}

# Data filtering
MIN_MATCH_DATE = "2019-01-01"  # Only use matches from this date onwards
SUPPORTED_FORMATS = ["T20", "ODI"]

# Cricket Data API (cricketdata.org)
CRICKET_DATA_API_KEY = os.getenv("CRICKET_DATA_API_KEY")
CRICKET_DATA_BASE_URL = "https://api.cricapi.com/v1"

# Market integrations (Wave 2: read-path readiness; Wave 5 Phase 6a: write-path)
POLYMARKET_CONFIG = {
    "enabled": os.getenv("POLYMARKET_ENABLED", "false").lower() == "true",
    "api_base_url": os.getenv("POLYMARKET_API_BASE_URL", "https://gamma-api.polymarket.com"),
    "clob_base_url": os.getenv("POLYMARKET_CLOB_BASE_URL", "https://clob.polymarket.com"),
    "chain_id": int(os.getenv("POLYMARKET_CHAIN_ID", "137")),
    # Read-only fields (Wave 2). Optional.
    "api_key": os.getenv("POLYMARKET_API_KEY"),
    "api_secret": os.getenv("POLYMARKET_API_SECRET"),
    "passphrase": os.getenv("POLYMARKET_PASSPHRASE"),
    # Write-path (Wave 5 Phase 6a). Required for live betting only.
    "private_key": os.getenv("POLYGON_PRIVATE_KEY") or os.getenv("POLYMARKET_PRIVATE_KEY"),
    "funder_address": os.getenv("POLYGON_FUNDER_ADDR") or os.getenv("POLYMARKET_FUNDER_ADDR"),
    # Polymarket signature_type: 0 = EOA, 1 = POLY_PROXY (Magic), 2 = GNOSIS_SAFE.
    # POLY_PROXY (1) is the Polymarket-default for accounts created via their
    # web UI; bot-managed wallets generated by bootstrap_polymarket_wallet.py
    # are EOAs (signature_type=0). Override via env if your wallet is different.
    "signature_type": int(os.getenv("POLYMARKET_SIGNATURE_TYPE", "0")),
}

# Wave 5 Phase 6c: Live betting risk gate config.
# All caps are enforced server-side in src/integrations/polymarket/risk_gate.py;
# the UI can re-check for UX but cannot bypass the server gate.
BETTING_CONFIG = {
    "mode": os.getenv("BETTING_MODE", "OFF").upper(),  # OFF | MANUAL | AUTO
    "max_deposit_usdc": float(os.getenv("BETTING_MAX_DEPOSIT", "200")),
    "max_per_bet_usdc": float(os.getenv("BETTING_MAX_PER_BET", "25")),
    # Floating per-bet cap as a fraction of the strategy's live bankroll.
    # When > 0 and a strategy_label is provided, overrides max_per_bet_usdc.
    # e.g. 0.225 = 22.5% of live bankroll. Grows/shrinks as bankroll moves.
    # Falls back to max_per_bet_usdc for untagged manual bets.
    "max_per_bet_fraction": float(os.getenv("BETTING_MAX_PER_BET_FRACTION", "0")),
    "max_per_day_usdc": float(os.getenv("BETTING_MAX_PER_DAY", "50")),
    "max_loss_per_day_usdc": float(os.getenv("BETTING_MAX_LOSS_PER_DAY", "30")),
    "auto_min_edge_pp": float(os.getenv("BETTING_AUTO_MIN_EDGE", "5.0")),
    # Comma-separated list (e.g. "moneyline,most_sixes"). Default to moneyline only;
    # the Wave 5 Phase 5 EV report should expand this list per-tournament.
    "auto_enabled_markets": [
        m.strip() for m in os.getenv("BETTING_AUTO_MARKETS", "moneyline").split(",") if m.strip()
    ],
    "kill_switch": os.getenv("BETTING_KILL_SWITCH", "0").strip() in ("1", "true", "True", "TRUE"),
    # Phase 7 scale-up gate thresholds (used by the dashboard "graduate envelope" flow).
    "scale_up_min_settled_bets": int(os.getenv("BETTING_SCALE_MIN_BETS", "50")),
    "scale_up_max_brier_drift": float(os.getenv("BETTING_SCALE_MAX_BRIER_DRIFT", "0.02")),
    # Wave 5.8: per-strategy caps for the 5-strategy live-betting envelope.
    # Each strategy_label in bet_ledger is independently capped so a single
    # strategy cannot monopolise the total deposit envelope.
    "max_deposit_per_strategy_usdc": float(os.getenv("BETTING_MAX_DEPOSIT_PER_STRATEGY", "100")),
    # Whitelist of strategy_labels allowed to place real (bet_kind='real') orders.
    # Empty list = no strategies are live; remove a name here to silence that
    # strategy without any code changes.
    "live_strategies": [
        s.strip() for s in os.getenv("BETTING_LIVE_STRATEGIES", "").split(",") if s.strip()
    ],
}

BETFAIR_CONFIG = {
    "enabled": os.getenv("BETFAIR_ENABLED", "false").lower() == "true",
    "app_key": os.getenv("BETFAIR_APP_KEY"),
    "username": os.getenv("BETFAIR_USERNAME"),
    "password": os.getenv("BETFAIR_PASSWORD"),
    "session_token": os.getenv("BETFAIR_SESSION_TOKEN"),
    # Optional for non-interactive login; not required for interactive/session-token mode.
    "cert_file": os.getenv("BETFAIR_CERT_FILE"),
    "key_file": os.getenv("BETFAIR_KEY_FILE"),
    "sso_base_url": os.getenv("BETFAIR_SSO_BASE_URL", "https://identitysso.betfair.com"),
    "login_path": os.getenv("BETFAIR_LOGIN_PATH", "/api/login"),
    "cert_login_path": os.getenv("BETFAIR_CERT_LOGIN_PATH", "/api/certlogin"),
    "keep_alive_path": os.getenv("BETFAIR_KEEP_ALIVE_PATH", "/api/keepAlive"),
    "betting_api_base_url": os.getenv("BETFAIR_BETTING_API_BASE_URL", "https://api.betfair.com/exchange/betting"),
}

# ELO Configuration
ELO_CONFIG = {
    "initial_rating": 1500,
    "k_factor_team": 32,  # K-factor for team ELO updates
    "k_factor_player_batting": 20,  # K-factor for player batting ELO
    "k_factor_player_bowling": 20,  # K-factor for player bowling ELO
    "rating_floor": 1000,  # Minimum possible rating
    "rating_ceiling": 2500,  # Maximum possible rating
}

# Model Configuration
MODEL_CONFIG = {
    "test_size": 0.2,
    "validation_size": 0.1,
    "random_state": 42,
    "epochs": 100,
    "batch_size": 32,
    "learning_rate": 0.001,
}

# Monte Carlo Simulation
SIMULATION_CONFIG = {
    "num_simulations": 10000,  # Number of match simulations to run
    "confidence_level": 0.95,  # For confidence intervals
    "chunk_size": 1000,  # Simulations per chunk for progress updates
}

# Performance / Parallelism Configuration (Apple M2 Pro optimization)
import multiprocessing
PARALLELISM_CONFIG = {
    "n_cpu_cores": multiprocessing.cpu_count(),
    "tf_inter_op_threads": max(4, multiprocessing.cpu_count() // 2),
    "tf_intra_op_threads": max(4, multiprocessing.cpu_count() // 2),
    "numpy_threads": 4,
    "n_workers": max(2, multiprocessing.cpu_count() - 2),  # For ProcessPoolExecutor
}

# Flask Configuration
class FlaskConfig:
    SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key-change-in-production")
    DEBUG = os.getenv("FLASK_DEBUG", "True").lower() == "true"
    HOST = os.getenv("FLASK_HOST", "127.0.0.1")
    PORT = int(os.getenv("FLASK_PORT", 5000))


# Logging Configuration
LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
            "level": "INFO",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "app.log",
            "formatter": "standard",
            "level": "DEBUG",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

# Feature Engineering Configuration
FEATURE_CONFIG = {
    "recent_form_matches": 10,  # Number of recent matches for form calculation
    "min_matches_for_stats": 5,  # Minimum matches for reliable statistics
    "innings_phases": {
        "powerplay": (0, 6),
        "middle": (6, 15),  # For T20, adjusted for ODI
        "death": (15, 20),
    },
}

# Ball outcome categories
BALL_OUTCOMES = {
    "runs": [0, 1, 2, 3, 4, 6],
    "extras": ["wide", "noball", "bye", "legbye"],
    "wickets": ["bowled", "caught", "lbw", "run out", "stumped", "hit wicket"],
}

# Known ICC teams safety net
# When a team is scraped from CREX but cannot be matched to the database,
# check this list. If the team is a known ICC member, auto-create it with
# the specified tier and default ELO. This prevents phantom "Unknown" teams
# from producing misleading predictions.
KNOWN_ICC_TEAMS = {
    # Full Members (Tier 1)
    'afghanistan': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1700.0, 'default_elo_odi_male': 1650.0, 'note': 'Cricsheet withheld all Afghanistan match data (Nov 2024) due to ICC women\'s cricket policy. ELO is manually estimated.'},
    'australia': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'bangladesh': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1600.0, 'default_elo_odi_male': 1600.0},
    'england': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'india': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'ireland': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1550.0, 'default_elo_odi_male': 1550.0},
    'new zealand': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'pakistan': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'south africa': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1650.0, 'default_elo_odi_male': 1650.0},
    'sri lanka': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1600.0, 'default_elo_odi_male': 1600.0},
    'west indies': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1600.0, 'default_elo_odi_male': 1600.0},
    'zimbabwe': {'tier': 1, 'team_type': 'international', 'default_elo_t20_male': 1550.0, 'default_elo_odi_male': 1550.0},
    # Top Associates (Tier 2)
    'canada': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1500.0, 'default_elo_odi_male': 1450.0},
    'hong kong': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1450.0, 'default_elo_odi_male': 1400.0},
    'namibia': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1550.0, 'default_elo_odi_male': 1500.0},
    'nepal': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1550.0, 'default_elo_odi_male': 1500.0},
    'netherlands': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1500.0, 'default_elo_odi_male': 1500.0},
    'oman': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1450.0, 'default_elo_odi_male': 1400.0},
    'papua new guinea': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1450.0, 'default_elo_odi_male': 1400.0},
    'scotland': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1550.0, 'default_elo_odi_male': 1500.0},
    'united arab emirates': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1500.0, 'default_elo_odi_male': 1450.0},
    'united states of america': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1500.0, 'default_elo_odi_male': 1450.0},
    'uganda': {'tier': 2, 'team_type': 'international', 'default_elo_t20_male': 1500.0, 'default_elo_odi_male': 1450.0},
}

