-- ============================================================================
-- TIERED ELO SYSTEM - Schema V3
-- ============================================================================
-- Add tier classifications for teams and tournament-based tier logic
-- Supports cross-pool normalization with asymmetric K-factors

-- Add tier columns to teams table (if not exists)
-- Note: SQLite doesn't support IF NOT EXISTS for ALTER TABLE ADD COLUMN
-- These statements will fail silently if columns already exist (handled in Python)

-- Try to add tier column (may already exist)
-- ALTER TABLE teams ADD COLUMN tier INTEGER DEFAULT 3;

-- Try to add tier_last_reviewed (may fail if exists)
-- ALTER TABLE teams ADD COLUMN tier_last_reviewed DATE;

-- Try to add tier_notes (may fail if exists)
-- ALTER TABLE teams ADD COLUMN tier_notes TEXT;

-- Ensure all teams have tier set (default to 3 if NULL)
UPDATE teams SET tier = 3 WHERE tier IS NULL;

-- Set tier_last_reviewed for teams that don't have it
-- This will only work if the column exists
-- UPDATE teams SET tier_last_reviewed = CURRENT_DATE WHERE tier_last_reviewed IS NULL;

-- Create index for fast tier lookups
CREATE INDEX IF NOT EXISTS idx_teams_tier ON teams(tier);

-- ============================================================================
-- Tournament Base Tiers Table
-- ============================================================================
-- Maps tournament patterns to base tier levels
-- Individual match tiers can adjust ±1 based on teams involved

CREATE TABLE IF NOT EXISTS tournament_tiers (
  tournament_pattern TEXT PRIMARY KEY,
  base_tier INTEGER CHECK(base_tier BETWEEN 1 AND 5) NOT NULL,
  notes TEXT
);

-- World Cups and Champions Events (Tier 1)
INSERT OR IGNORE INTO tournament_tiers VALUES 
  ('%T20 World Cup%', 1, 'Premier global tournament'),
  ('%World Cup%', 1, 'Premier global tournament'),
  ('%Champions Trophy%', 1, 'Premier ICC event'),
  ('%World Twenty20%', 1, 'Legacy World Cup naming'),
  ('%ICC Men''s T20 World Cup%', 1, 'Full ICC World Cup title'),
  ('%ICC Women''s T20 World Cup%', 1, 'Full ICC World Cup title');

-- Bilateral International (Full Members) - Tier 2
INSERT OR IGNORE INTO tournament_tiers VALUES
  ('%tour of%', 2, 'Bilateral international series'),
  ('%T20I Series%', 2, 'T20 International series'),
  ('%Triangular%', 2, 'Multi-nation tournament'),
  ('%Tri-Series%', 2, 'Tri-nation series'),
  ('%Tri-Nation%', 2, 'Tri-nation series');

-- Premier Franchise Leagues - Tier 3
INSERT OR IGNORE INTO tournament_tiers VALUES
  ('%Indian Premier League%', 3, 'IPL'),
  ('%Big Bash League%', 3, 'BBL'),
  ('%Caribbean Premier League%', 3, 'CPL'),
  ('%Pakistan Super League%', 3, 'PSL'),
  ('%The Hundred%', 3, 'The Hundred'),
  ('%Super Smash%', 3, 'New Zealand domestic T20'),
  ('%Bangladesh Premier League%', 3, 'BPL'),
  ('%Lanka Premier League%', 3, 'LPL'),
  ('%Women''s Premier League%', 3, 'WPL India');

-- Regional/Associate Tournaments - Tier 4
INSERT OR IGNORE INTO tournament_tiers VALUES
  ('%Africa%', 4, 'African regional'),
  ('%Asia Cup%', 4, 'Asian regional'),
  ('%ACC%', 4, 'Asian Cricket Council'),
  ('%Continental Cup%', 4, 'Associate regional'),
  ('%ICC World Cup Qualifier%', 4, 'World Cup qualifying'),
  ('%East Asia%', 4, 'Regional Asian'),
  ('%Europe%', 4, 'European regional');

-- Domestic/Minor Leagues - Tier 5
INSERT OR IGNORE INTO tournament_tiers VALUES
  ('%County%', 5, 'English county cricket'),
  ('%Trophy%', 5, 'Domestic trophy'),
  ('%Challenge%', 5, 'Domestic challenge'),
  ('%T20 Blast%', 5, 'English domestic T20'),
  ('%Vitality Blast%', 5, 'English domestic T20'),
  ('%Syed Mushtaq Ali%', 5, 'Indian domestic T20'),
  ('%Inter-Provincial%', 5, 'Irish domestic');

-- Catch-all patterns (lowest priority)
INSERT OR IGNORE INTO tournament_tiers VALUES
  ('%Cup%', 5, 'Generic cup tournament'),
  ('%Series%', 4, 'Generic series'),
  ('%Tournament%', 4, 'Generic tournament');

-- ============================================================================
-- Promotion Review Flags Table
-- ============================================================================
-- Tracks teams that should be reviewed for tier promotion/demotion
-- Auto-generated by calculator, requires manual admin approval

CREATE TABLE IF NOT EXISTS promotion_review_flags (
  flag_id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id INTEGER NOT NULL REFERENCES teams(team_id),
  format TEXT NOT NULL CHECK(format IN ('T20', 'ODI')),
  gender TEXT NOT NULL CHECK(gender IN ('male', 'female')),
  current_tier INTEGER NOT NULL CHECK(current_tier BETWEEN 1 AND 5),
  suggested_tier INTEGER NOT NULL CHECK(suggested_tier BETWEEN 1 AND 5),
  trigger_reason TEXT NOT NULL,
  current_elo REAL NOT NULL,
  months_at_ceiling INTEGER,
  cross_tier_record TEXT,
  flagged_date DATE DEFAULT CURRENT_DATE,
  reviewed BOOLEAN DEFAULT FALSE,
  reviewed_date DATE,
  reviewer_notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(team_id, format, gender, reviewed)
);

CREATE INDEX IF NOT EXISTS idx_promotion_flags_pending ON promotion_review_flags(reviewed, flagged_date);
CREATE INDEX IF NOT EXISTS idx_promotion_flags_team ON promotion_review_flags(team_id, format, gender);

